### ISSUE TITLE
Cannot convert method group `IsError' to non-delegate type `bool'. Consider using parentheses to invoke the method (CS0428) (Assembly-CSharp)

### ISSUE THREAD

**Issue by beersheba** [googlecodelabs/arcore-intro#4]
Error in code on page 3 - Set up the SceneController
`else if (Session.Status.IsError)`

> Cannot convert method group `IsError' to non-delegate type `bool'. Consider using parentheses to invoke the method (CS0428) (Assembly-CSharp)

Must be
`else if (Session.Status.IsError())`

**Comment by CJRobertson** [comment]
I get the same error. Using the suggestion from the OP's post fixes this issue.

**Comment by kai-dream** [comment]
Hi, 

Thanks for trying out the codelab. Yes, there's minor error in the webpage, we missed the "()".
I've fixed that.

Cheers
