### ISSUE TITLE
error CS1061: Type `ScoreboardController' does not contain a definition for `SetSelectedPlane' and no extension method `SetSelectedPlane' of type `ScoreboardController' could be found. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by vivekghanchi** [googlecodelabs/arcore-intro#6]

**Comment by kai-dream** [comment]
Hi,

This function is to be added when you follow instructions in this [codelab](https://codelabs.developers.google.com/codelabs/arcore-intro/). You can also refer to the files in https://github.com/googlecodelabs/arcore-intro/tree/master/SlitherAR-Complete for reference of completed project.

Cheers,
Kai
